function Phi = evaluateFaceBasis(x, xf, Qf, t1, t2, n, Af, m20, m02)
% evaluate all six face traction basis functions simultaneously

    local = Qf' * (x - xf);
    
    xt = local(1);
    yt = local(2);
    
    Phi = [ ...
        t1 / Af, ...
        t2 / Af, ...
        n / Af, ...
        (-yt*t1 + xt*t2) / (Af*sqrt(m20+m02)), ...
        (xt*n) / (Af*sqrt(m20)), ...
        (yt*n) / (Af*sqrt(m02)) ];

end